version: '3.8'

services:
  # Serviço do frontend
  frontend:
    image: dalexandrias/fitfood:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: fitfood-frontend
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - green-food-network
    # Se precisar de variáveis de ambiente
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://localhost:3001/api/v1
      - VITE_PRODUCTS_API_URL=http://localhost:8082/v1/product
      - VITE_AUTH_API_URL=/auth
      - VITE_TOKEN_KEY=fitfood_auth_token
      - VITE_REFRESH_TOKEN_KEY=fitfood_refresh_token
      - VITE_USER_INFO_KEY=fitfood_user_info
      - VITE_REMEMBER_ME_KEY=fitfood_remember_me
      - VITE_SESSION_TIMEOUT=1800000
    # Volumes para desenvolvimento (opcional, comentado por padrão)
    # volumes:
    #   - ./src:/app/src

  # Serviço de API mock (opcional, para desenvolvimento)
  # Descomente se precisar de um servidor de API para testes
  # api-mock:
  #   image: stoplight/prism:4
  #   container_name: fitfood-api-mock
  #   command: mock -h 0.0.0.0 /api/openapi.yaml
  #   ports:
  #     - "4010:4010"
  #   volumes:
  #     - ./api:/api
  #   networks:
  #     - fitfood-network

networks:
  green-food-network:
    external: true
